[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-3-Clause",
  "BSD-2-Clause",
  "Apache-2.0 WITH LLVM-exception",
  "ISC",
  "MPL-2.0",
  "Zlib",
  "CC0-1.0",
  "Unicode-DFS-2016",
  "Unlicense"
]