export const AGE_CREDENTIAL_GROUP = 'Verified Age';
export const RESIDENCE_CREDENTIAL_GROUP = 'Verified Residence';
export const EMPLOYMENT_CREDENTIAL_GROUP = 'Verified Employment';
export const HUMANITY_CREDENTIAL_GROUP = 'Verified Humanity';

export const CREDENTIALS_WITH_INPUT = [
  AGE_CREDENTIAL_GROUP,
  RESIDENCE_CREDENTIAL_GROUP,
  EMPLOYMENT_CREDENTIAL_GROUP,
];

export const CREDENTIALS = [
  AGE_CREDENTIAL_GROUP,
  RESIDENCE_CREDENTIAL_GROUP,
  EMPLOYMENT_CREDENTIAL_GROUP,
  HUMANITY_CREDENTIAL_GROUP,
];
