name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [ 1.76.0 ]

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      run: |
        rustup update ${{ matrix.rust }} --no-self-update
        rustup default ${{ matrix.rust }}
        rustup component add rustfmt
        rustup component add clippy

    - name: Check Format
      run: cargo fmt --all -- --check

      # fails if lockfile is out of date
      # https://users.rust-lang.org/t/check-if-the-cargo-lock-is-up-to-date-without-building-anything/91048/5
    - name: Cargo Lockfile Check
      run: cargo update --workspace --locked
